### ISSUE TITLE
Adaptor content is 0 unless we specify --adapters

### ISSUE THREAD

**Issue by edgardomortiz** [smithlabcode/falco#16]
Thanks for the program, we had been looking for a faster replacement for FastQC.

However, in a default run with `falco 0.2.4` (from `bioconda`), the **Adaptor Content** plot is empty unless we add `--adapters` and the path to the adapter list file (which by the way seems not to be shipped in the `conda` installation, but I may be wrong on that).

Edgardo

**Comment by guilhermesena1** [comment]
ok I could reproduce the problem you were referring to! It was a very silly bug that slipped under the radar for me. This should be fixed at f035b2e . Thank you so much for providing the data it was very helpful to find those problems!

**Comment by edgardomortiz** [comment]
Excellent and thanks for the quick response!

**Comment by guilhermesena1** [comment]
I'll close this issue for now but feel free to reopen if you run into any problems related to this topic.
