### ISSUE TITLE
Does not correctly decode old Illumina Phred score encoding

### ISSUE THREAD

**Issue by shigita** [smithlabcode/falco#18]
I ran `Falco 0.2.4` and `FastQC` on old Illumina data, and noticed that the recognition of Phred score encoding differs between programs as follow:
`Falco` recognized as Illumina 1.9, and `Per base sequence quality` and `Per seqence quality score` look incorrect.
`FastQC` recognized as Illumina 1.5, and everything looks fine.

Attached, small example of old fastq and output from each program.
- [read_1.fastq.gz](https://github.com/smithlabcode/falco/files/7127934/read_1.fastq.gz)
- [falco_result.zip](https://github.com/smithlabcode/falco/files/7127952/falco_result.zip)
- [fastqc_result.zip](https://github.com/smithlabcode/falco/files/7127954/fastqc_result.zip)

Here are the commands I ran:
```
# Falco
falco --nogroup read_1.fastq.gz --outdir falco_result

# FastQC
fastqc --nogroup read_1.fastq.gz --outdir fastqc_result
```
I hope these help reproduce the problem.
Thanks in advance.

**Comment by guilhermesena1** [comment]
Hello,

Thank you for providing the data to reproduce the issue! We have some issues open regarding quality distributions on both nanopore and legacy phred32 from Illumina. Currently the program assumes everything is Illumina, and we will address this problem in the upcoming release. I sincerely apologize for the inconvenience!

**Comment by guilhermesena1** [comment]
with your data I was able to push a fix for the problem at baad210 . I haven't tested it thoroughly, but for your dataset at least it now gives the same plots for per base sequence quality, basic statistics and per sequence quality scores. Thank you once again for communicating the issue!

**Comment by shigita** [comment]
I have confirmed that it works even on my whole data!
Thank you very much for your prompt response :blush:

**Comment by guilhermesena1** [comment]
glad to hear it! I'll close this for now just to keep track of current issues that need addressing but feel free to reopen if you run into any problems with the current push.
