### ISSUE TITLE
add some additional information to the README for compilation

### ISSUE THREAD

**Issue by estolle** [smithlabcode/falco#2]
Hi there

After just encountering some errors/problems installing Falco by compilation, I think the ReadMe would benefit from adding a few specifics how exactly to compile. after trying around a while, my working procedure was:

cd falco-0.2.1
sudo autoreconf -fvi
sudo autoconf
sudo ./configure CXXFLAGS="-O3 -Wall" --enable-hts
sudo make all
sudo make install

Best,
Eckart

**Comment by guilhermesena1** [comment]
Hi Eckart,

Thank you very much for the suggestion. The commands we described on the README file should be run when downloading a stable release (in the "releases" link above), as opposed to cloning the repository. I definitely agree that the instructions were not clear enough so I updated the README to hopefully clarify all steps for compilation.

Best,
Guilherme

**Comment by andrewdavidsmith** [comment]
Sorry -- closed by accident. @estolle Did you want to leave this open?

**Comment by estolle** [comment]
great, thanks for the clarification.
