### ISSUE TITLE
Segmentation fault      (core dumped) for zero length reads

### ISSUE THREAD

**Issue by y9c** [smithlabcode/falco#26]
After trimming, some reads might be 0 in length. falco can not deal with these reads correctly.

**Comment by guilhermesena1** [comment]
I'm so sorry it took this long to reach out but I think I fixed the problem. I'll make a new release in the coming days to address this. Commit  64d98d should not crash on empty reads. Definitely a very important bug to address!

**Comment by y9c** [comment]
Thanks!

**Comment by y9c** [comment]
Hi @guilhermesena1,

The new patch create more bugs. When there is a empty read, falco will keep running, but it can not generate any output, and terminate with the following error.

```
 terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    3085727 abort (core dumped)  falco ./test.fq.gz -o test
```

**Comment by y9c** [comment]
This error is not cause by zero length reads. Any fastq input can cause this error.

**Comment by y9c** [comment]
I would like to know why zero length reads is not in the "Sequence Length Distribution" plot? Thanks.

**Comment by guilhermesena1** [comment]
hey.

for the first error, I think your call has reversed the parameters. Falco takes multiple FASTQC as inputs, and this requires the file names to be the last parameters in the call, so instead of
```
falco test.fq.gz -o test
```
it should be
```
falco -o test test.fq.gz
```

I'll look into the plot issue right now.

**Comment by y9c** [comment]
Thank you for the update

**Comment by y9c** [comment]
Hi @guilhermesena1 

It seem that falco is still have bugs in dealing short reads. When input reads are too short, the html report can not be generated.

Error message:
```
terminate called after throwing an instance of 'std::length_error'
```

test input:

```
@test
TTACAGCACT
+
FFFFFFFFFF
```
