### ISSUE TITLE
Options for using falco without root privilege 

### ISSUE THREAD

**Issue by moldach** [smithlabcode/falco#3]
The installation instructions for `falco` appear to require root privileges.

```
[moldach@cedar1 falco-0.2.1]$ make install
make[1]: Entering directory '/home/moldach/bin/falco-0.2.1'
 /cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/mkdir -p '/usr/local/bin'
  /cvmfs/soft.computecanada.ca/custom/bin/install -c falco falcodiff '/usr/local/bin'
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/install: cannot create regular file '/usr/local/bin/falco': Permission denied
/cvmfs/soft.computecanada.ca/nix/var/nix/profiles/16.09/bin/install: cannot create regular file '/usr/local/bin/falcodiff': Permission denied
make[1]: *** [Makefile:407: install-binPROGRAMS] Error 1
make[1]: Leaving directory '/home/moldach/bin/falco-0.2.1'
make: *** [Makefile:935: install-am] Error 2
```

Similarly, [Compute Canada staff do not want us using `conda`](https://docs.computecanada.ca/wiki/Anaconda/en).

I'm wondering if you have a `singularity` container or another preferred method for academics using HPCs.

Thank you

**Comment by guilhermesena1** [comment]
Hi Matthew,

Thank you for your message. Indeed makefiles will by default try to install the binary into your `/usr/bin` or `/usr/local/bin` , directory which hpc users often don't have privileges to. You can specify different paths when you run `configure` using the `--prefix` directive, namely:
```
./configure --prefix=/path/to/where/you/install/programs
```
Personally I usually leave binaries in the same directory as the source code using the following:
```
./configure --prefix=$PWD
```
this will create a `bin` directory where you downloaded the source and you can run the program by running `./bin/falco`, or adding the bin path to your `PATH` variable, etc.

Let me know if you are able to compile and run this way!

**Comment by moldach** [comment]
Hi this works great. 

I have a feature request so I'll close this and open a new issue. Thanks!
