### ISSUE TITLE
falco v1.1.0 hangs when processing bam file

### ISSUE THREAD

**Issue by msnyder424** [smithlabcode/falco#41]
hi! i'm trying to use the most recent version of falco. i created a conda env with a recipe file as below.
```
name: falco_env
channels:
  - conda-forge
  - bioconda
dependencies:
 - falco=1.1.0
```

in that env when i tried processing a 73M bam file the output looked like so:
```
[limits]        using default limit cutoffs (no file specified)
[adapters]      using default adapters (no file specified)
[contaminants]  using default contaminant list (no file specified)
[Wed Sep 21 16:03:09 2022] Started reading file data/DS-366791.hg19.bam
[Wed Sep 21 16:03:09 2022] reading file as BAM format
[running falco|===================================================|100%]
[Wed Sep 21 16:03:18 2022] Finished reading file
[Wed Sep 21 16:03:18 2022] Writing text report to falco_conda_test//fastqc_data.txt
[Wed Sep 21 16:03:18 2022] Writing HTML report to falco_conda_test//fastqc_report.html
```

but then it just hung for about an hour, after which point i just killed it. fastqc_data.txt had some data in it, but fastqc_report.html and summary.txt were empty files. i was able to process the exact same bam file with falco v1.0.0 also installed with conda. seems like a bug report here.

thanks!

**Comment by andrewdavidsmith** [comment]
@msnyder424 Thanks very much for this! I think your recipe indicating 1.1.0 might be just a bit out of date, and there's a chance this is a bug we very recently fixed. Is there any chance you can try again with the 1.2.1, which is the most recent? I think you'd be best ensuring it was the most recent build. I get the sense with you showing the recipe you'd be able to navigate which build is installed, but otherwise I'm happy to help.

**Comment by guilhermesena1** [comment]
Hello

I second that. This seems very similar to issue #40 (though the issue discussion has diverted to other problems). If at all possible could you confirm that the problem persists if you run `conda update -c bioconda falco` (and ensure that `falco --version` says it is 1.2.1)? Thank you!

**Comment by msnyder424** [comment]
@andrewdavidsmith which build is the most recent:
falco                          1.2.1      h3d8d00f_2  bioconda
falco                          1.2.1      h9f5acd7_0  bioconda
falco                          1.2.1      h9f5acd7_1  bioconda

**Comment by andrewdavidsmith** [comment]
Thanks again @msnyder424 We will see what we can do to make sure it's cleaner when people have to look at those build ids. We had some challenges recently, hence the 3 builds for the same version.

**Comment by msnyder424** [comment]
perfect. i'll close this since. sorry about the outdated version. i think when i looked a few weeks ago 1.1.0 was the most recent. @guilhermesena1 if only there was a conda test repo just like the pypi test repo...
