### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lskatz** [smithlabcode/falco#58]
The documentation is not being rendered on readthedocs.io

**Comment by andrewdavidsmith** [comment]
@lskatz Thanks for this!! I'll see what I can do.

**Comment by andrewdavidsmith** [comment]
@lskatz This is fixed in PR #3e4f0ad but it currently is only reflected in the latest rather than stable version on rtd. Currently the working version is showing as default, but it might take some time until a new falco release is made, which would update the "stable" version of the docs.
