### ISSUE TITLE
falco crashes with multiQC version 1.9

### ISSUE THREAD

**Issue by pbiology** [smithlabcode/falco#7]
Tried running multiqc on a falco output directory and it crashed. Here is the error log:
 ```
[WARNING]          fastqc : Sample had zero reads: 'falco_out | DNA67062_S3_L001_R1_001'
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    falco_out/fastqc_data.txt
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/home/xlinak/conda_envs/conda_med/lib/python3.8/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/home/xlinak/conda_envs/conda_med/lib/python3.8/site-packages/multiqc/modules/fastqc/fastqc.py", line 117, in __init__
    self.overrepresented_sequences()
  File "/home/xlinak/conda_envs/conda_med/lib/python3.8/site-packages/multiqc/modules/fastqc/fastqc.py", line 824, in overrepresented_sequences
    max_pcnt   = max( [ float(d['percentage']) for d in self.fastqc_data[s_name]['overrepresented_sequences']] )
ValueError: max() arg is an empty sequence
============================================================
```

**Comment by pbiology** [comment]
Multiqc version was 1.9 and falco 0.2.1

**Comment by guilhermesena1** [comment]
Hi Anders,

I will try to reproduce the problem on my end. However, if possible, would you be able to share the `fastqc_data.txt` and `summary.txt` files inside the  `falco_out`  directory generated by your output so I can try to reproduce? Thank you!

**Comment by guilhermesena1** [comment]
Hi Anders,

Thank you for reporting the problem. I was able to reproduce the error with my own dataset and indeed it seems like we had some inconsistencies between the fastqc and falco outputs that were making MultiQC not be able to parse the "Sequence Length Distribution" module. We also were printing the headers of the "Overrepresented sequences" module even when it was empty. I pushed a change that should fix the problem, but that will require you cloning and compiling the program again. I apologize for the inconvenience!

We are letting some problems pile up and will hopefully soon build a release that addresses all of them. Please let us know if this solves the problem and/or if you run into further ones.

**Comment by pbiology** [comment]
Hey Guilherme.

Thanks for the quick reply! Great that you've gotten the problem fixed. However, I was hoping to run falco as part of general pipeline, and we are relying on conda for managing the environment and I'd like to keep the custom parts down to a bare minimum.

Could I ask why you don't include a more stable output form, perhaps as a supplement to the fastqc like output, and write a specific falco module for multiQC? (https://multiqc.info/docs/#custom-content).

Maybe this could be a more stable way to integrate into multiQC, and also have falco being q part of the list of modules available in multiQC (raising awareness). 
As we are developing pipelines for running in cloud based pipelines, core-minutes become important, and having a fast tool (like falco) is really high up on the priority list.

**Comment by andrewdavidsmith** [comment]
@pbiology I know this is old. I'm closing this issue, but opened another referencing your query about how you used falco in your pipeline.
