### ISSUE TITLE
Different progress bar behavior?

### ISSUE THREAD

**Issue by pdimens** [smithlabcode/falco#76]
In the CI tests I use for [harpy](https://www.github.com/pdimens/harpy), the tests using falco in a container suddenly began to fail, seemingly due to the progress bar printing *despite using the --quiet flag**. See the actual error [here](https://github.com/pdimens/harpy/actions/runs/11504008454/job/32023423535?pr=150#step:7:298) 

Falco was invoked via a snakemake workflow with the command:
```bash
falco --quiet --threads {threads} -skip-report -skip-summary -data-filename {output} {input}
```

It's unclear why the progress bar seems to still be printing during the CI tests, maybe something changed in the falco code?

**Comment by andrewdavidsmith** [comment]
@pdimens There's obviously a problem, but i don't think it's the progress bars. The link shows this:
```console
[=================================-                        ] 350672/591427  59%
[===================================\                      ] 363683/591427  61%
[===================================/                      ] 369203/591427  62%
[====================================-                     ] 379190/591427  64%
[=====================================\                    ] 384844/591427  65%
[=====================================/                    ] 393697/591427  66%
[======================================-                   ] 396264/591427  67%
```
Falco progress should look like this:
```console
[running falco|================================                   | 63%]
[running falco|================================                   | 64%]
[running falco|=================================                  | 65%]
[running falco|=================================                  | 66%]
[running falco|==================================                 | 67%]
```
Can you dig a bit more? I see a "no space left on device" in those logs.
